### ISSUE TITLE
ImportError: No module named hub

### ISSUE THREAD

**Issue by lancexiang** [kazuto1011/grad-cam-pytorch#12]
Here i met with a error when i run your code demo1.
![image](https://user-images.githubusercontent.com/22250092/56343653-e8a85480-61ed-11e9-9e9b-a342870f9eb3.png)

And in the grad_cam.py line 68 the `super()` raise a expection:
`TypeError: super() takes at least 1 argument (0 given)`

**Comment by kazuto1011** [comment]
Thank you for reporting. This is due to the python version. Fixed!
