### ISSUE TITLE
There is a bug in Demo 3

### ISSUE THREAD

**Issue by mymuli** [kazuto1011/grad-cam-pytorch#16]
File "/home/muli/.torch/hub/pytorch-ported-models_master/models/classification/resnet.py", line 161
    f"block{i+1}",
                ^
SyntaxError: invalid syntax
**
![bug](https://user-images.githubusercontent.com/37521721/62272685-3465cd80-b46e-11e9-9b0d-caea2e274728.png)
**

**Comment by kazuto1011** [comment]
Thank you for reporting the issue. It works with Python 3.+.

**Comment by mymuli** [comment]
@kazuto1011 ， **F-string(f"xxxx")** only appeared in Python 3.6, my Python is 3.5, so the program reported an error.
In addition, I would like to ask if this code is suitable for image **multi-label classification** tasks?

**Comment by kazuto1011** [comment]
Oh, you're right. Thank you, I'll modify the repository or fix README. 

https://github.com/kazuto1011/grad-cam-pytorch/blob/97afb3b35d71bf9f03a80e740e69ac2d89a4d27e/grad_cam.py#L28-L31

With multiple ids, you can easily create the multi-label backpropagation mask although it's no longer "one-hot".

**Comment by kazuto1011** [comment]
Removed demo 3 due to its redundancy.
