### ISSUE TITLE
Grad-CAM with Pythia

### ISSUE THREAD

**Issue by Karol-G** [kazuto1011/grad-cam-pytorch#18]
Hi again,

I integrated Grad-CAM into the vqa-model pythia. Pythia is a pipeline of multiple networks (multiple inputs, one output). For me the interesting route through the network is the following: First the input image is feed through a resnet152. The resulting features and features from other networks are then feed through the pythia network. The result is the prediction. I am currently doing it like this that I wrapped GradCAM around the resnet152 model and the pythia model seperatly. You sadly cannot wrap both together :/ Then I call backward only on the pythia model and call generate at layer '7' of the resnet152 model.

Code looks similar to this:
```
resnet125_model = GradCAM(model=resnet125_model)
pythia_model= GradCAM(model=pythia_model)
features = resnet125_model.forward(input_image)
# Add features from all networks to feature list
# ...
probs, ids = pythia_model.forward(feature_list)
pythia_model.backward(ids=ids [:, [0]])
regions = resnet125_model.generate(target_layer="7")
```

Is this approach correct? Because I am getting for most images seemingly correct results.
Should I do resnet125_model.backward too and if yes how?

**Comment by kazuto1011** [comment]
Yes, it should work in the connected computational graphs, however, it requires different Grad-CAM for each stage. I think it is a bit complex to do in a such situation since I made this repo just for single classification models. If you want to use the wrapper intact, I recommend wrapping your models as well like:
 
```py
class Pythia(nn.Module):
    def __init__(self, resnet152, pythia):
        self.resnet152 = resnet152
        self.pythia = pythia
        # anything else
        
    def forward(images):
        features = self.resnet152(images)
        # anything else
        logits = self.pythia(features)
        return logits

model = Pythia(resnet152, pythia)
model_cam = GradCAM(model=model)
```

Otherwise, without GradCAM class:
```py
cam_fmaps = None
cam_grads = None

def forward_hook(module, input, output):
     cam_fmaps = output.clone().detach()

def backward_hook(module, input, output):
     cam_grads = output[0].clone().detach()

# layer "7"
resnet152[7].register_forward_hook(forward_hook)
resnet152[7].register_backward_hook(backward_hook)

# normal forward and backward
# feature <- resnet152(image)
# feature <- any other models
# prediction <- pythia(features)
masked_prediction.backward(retain_graph=True)
```

Then you can generate Grad-CAM maps from the `cam_fmaps` and `cam_grads` like:
https://github.com/kazuto1011/grad-cam-pytorch/blob/e59ab185aa0ec5330d12d043a35b421c912ba45a/grad_cam.py#L163-L176

**Comment by Karol-G** [comment]
Thank you for the great answer! I did the first method and it seems to work :)

**Comment by purvaten** [comment]
Hi @Karol-G would it be possible for you to share your implementation of grad-cam for Pythia?

**Comment by Karol-G** [comment]
Hi,

sure, no problem. I have put the necessary classes into a gist https://gist.github.com/Karol-G/29a63098b07b79b6cbfad2f8e8a69da4
However I did this as a semester project and the code grew over time. So the code is very ugly and there is no documentation. I still hope it helps you though.

I also (coincidentally) released a framework just today https://github.com/Karol-G/Gcam for easy usage of Grad-Cam and etc. However the framework is only tested with classification and segmentation so I don't know if it will work as easily with VQA too.

Best
Karol

**Comment by purvaten** [comment]
@Karol-G This is great thank you so much. Would it also be possible for you to share the pythia.yaml and detectron_model.yaml config files?

**Comment by Karol-G** [comment]
Of course. I added the pythia.yaml to the gist. However it seems that I lost the detectron_model.yaml...

There are two different detectron_model.yaml files available online maybe they can help you as a guide:
https://dl.fbaipublicfiles.com/pythia/detectron_model/e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512.yaml (from this post https://github.com/facebookresearch/mmf/issues/30)
https://dl.fbaipublicfiles.com/pythia/detectron_model/detectron_model.yaml (from this post https://github.com/facebookresearch/mmf/issues/100)

The Pythia implementation I used was from this post originally: https://github.com/facebookresearch/mmf/issues/204
Maybe the guy who posted it can help you as well :)

Best
Karol
