### ISSUE TITLE
Issue with adaptive_avg_pool2d

### ISSUE THREAD

**Issue by duvi86** [kazuto1011/grad-cam-pytorch#31]
Hi, I see this kind of errors while running your code. Do you have an idea why ?

tensor([[-7.2651e-02,  3.3111e-04, -3.9845e-02, -8.2188e-04, -7.3406e-02,
         -5.8559e-02, -2.9483e-04, -7.7205e-04,  9.9348e-02,  8.5495e-02,
          3.3119e-04, -4.5217e-04,  2.3080e-04, -7.3062e-02,  7.6724e-02,
          1.1599e-03, -9.4273e-02, -1.0095e-03, -9.1842e-02,  1.1479e-02,
         -2.4315e-04, -8.7727e-04, -4.3297e-05,  4.6699e-04, -8.8610e-02,
          9.0534e-04,  1.0777e-03,  1.1020e-03,  3.7943e-04, -1.5738e-04,
          1.9025e-06, -1.1773e-03, -5.9867e-04, -1.0296e-01, -7.1966e-04,
         -5.4647e-02,  8.8068e-04,  8.4652e-05, -7.8065e-04, -2.1680e-02,
          7.4625e-02, -2.6460e-04,  2.2213e-04,  1.4736e-05,  1.0328e-03,
          9.8224e-02, -1.2822e-01,  1.2817e-01,  3.5466e-04, -1.7925e-04,
         -2.7482e-02,  1.2518e-01, -1.2606e-03,  3.2432e-04,  9.5974e-04,
          3.0479e-04, -1.1363e-03,  6.3062e-04,  8.9529e-02,  6.8524e-04,
         -3.0786e-04,  6.2523e-04,  1.1102e-03, -5.3212e-04],
        [-7.2651e-02,  3.3111e-04, -3.9845e-02, -8.2188e-04, -7.3406e-02,
         -5.8559e-02, -2.9483e-04, -7.7205e-04,  9.9348e-02,  8.5495e-02,
          3.3119e-04, -4.5217e-04,  2.3080e-04, -7.3062e-02,  7.6724e-02,
          1.1599e-03, -9.4273e-02, -1.0095e-03, -9.1842e-02,  1.1479e-02,
         -2.4315e-04, -8.7727e-04, -4.3297e-05,  4.6699e-04, -8.8610e-02,
          9.0534e-04,  1.0777e-03,  1.1020e-03,  3.7943e-04, -1.5738e-04,
          1.9025e-06, -1.1773e-03, -5.9867e-04, -1.0296e-01, -7.1966e-04,
         -5.4647e-02,  8.8068e-04,  8.4652e-05, -7.8065e-04, -2.1680e-02,
          7.4625e-02, -2.6460e-04,  2.2213e-04,  1.4736e-05,  1.0328e-03,
          9.8224e-02, -1.2822e-01,  1.2817e-01,  3.5466e-04, -1.7925e-04,
         -2.7482e-02,  1.2518e-01, -1.2606e-03,  3.2432e-04,  9.5974e-04,
          3.0479e-04, -1.1363e-03,  6.3062e-04,  8.9529e-02,  6.8524e-04,
         -3.0786e-04,  6.2523e-04,  1.1102e-03, -5.3212e-04]], device='cuda:0')
File "\lib\site-packages\torch\nn\functional.py", line 926, in adaptive_avg_pool2d
    return torch._C._nn.adaptive_avg_pool2d(input, _output_size)
RuntimeError: shape '[2, 64, 1, 1]' is invalid for input of size 1

**Comment by kazuto1011** [comment]
My code resizes an input image to 224x224. Is it too small for your model?
https://github.com/kazuto1011/grad-cam-pytorch/blob/fd10ff7fc85ae064938531235a5dd3889ca46fed/main.py#L68
