### ISSUE TITLE
unsupervised learning

### ISSUE THREAD

**Issue by daniiki** [kazuto1011/grad-cam-pytorch#35]
Hi, 
I have a question regarding the usability of grad-cam. Is it also possible to use grad-cam for unsupervised learning, especially image clustering, where I have no labels?

**Comment by pshwetank** [comment]
@daniiki  that's indeed an interesting aspect to look at. Although, you have to remember that gradient heatmap might not be always the best semantic segmentation for the task. It might be true in some cases where features are clear but not always se rve your purpose. But I strongly feel there can be a sweet spot you can target.
For example, you can train a network a classify apple vs not-apple images and then use grad-cam to segment few key pixels present in unseen apple images. The segmentation will not be as sharp compared to human labelled segmentation, but from an unsupervised perspective, even if you are getting this much without any human intervention, it is definitely great.
