### ISSUE TITLE
How can I load & run my own trained convnet model in your grad-cam?

### ISSUE THREAD

**Issue by bemoregt** [kazuto1011/grad-cam-pytorch#5]
Hi, @kazuto1011 

How can I load & run my own trained convnet model in your grad-cam?

My convnet(CNN) is a 34-layer's resnet, trained using my image datasets.

Thanks in advance.

form @bemoregt.

**Comment by kazuto1011** [comment]
You can find the solution here #3 . Basically, you only have to replace the model instance.

**Comment by bemoregt** [comment]
Hi, @kazuto1011 

Thanks a lot.

I solved It.
