### ISSUE TITLE
Process multiple image inputs at the same time

### ISSUE THREAD

**Issue by oyxhust** [kazuto1011/grad-cam-pytorch#8]
I find that the current code can only support the single image input. Can I input a batch of images to get the grad-cam outputs?

**Comment by kazuto1011** [comment]
Updated #9! Using my sample, now you can specify batch images like:

```bash
python main.py demo1 -a resnet152 \
                     -t layer4 \
                     -i a.png -i b.jpg -i c.bmp -i ...
```

Or you can import the wrapper classes into your projects.
